services:
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4.1.2-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      # Increase heartbeat timeout for long-running processes
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit heartbeat 60"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      # Add custom rabbitmq configuration
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - app-network

  minio-client:
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      - minio
    networks:
      - app-network
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc mb -p local/${S3_BUCKET};
        mc policy set public local/${S3_BUCKET};
        exit 0;
      "

volumes:
  minio_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge
